# Reference: 
# 1. run command "man vmstat" 
# 2. https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/etc/dcgm-exporter/dcp-metrics-included.csv

metrics_descriptions = {
    "cpu_vmstat_cpu_id": "Percentage of idle CPU",
    "cpu_vmstat_cpu_sy": "Percentage of CPU time spent on kernel processes",
    "cpu_vmstat_cpu_us": "Percentage of CPU time spent on non-kernel processes",
    "cpu_vmstat_cpu_wa": "Percentage of CPU time spent waiting for Input/Output",
    "cpu_vmstat_io_bi": "Blocks received from a block device (KB/s)",
    "cpu_vmstat_io_bo": "Blocks sent to a block device (KB/s)",
    "cpu_vmstat_mem_buff": "Total memory used as a data buffer (MB)",
    "cpu_vmstat_mem_cache": "Total memory to cache disk I/O (Page Cache) (GB)",
    "cpu_vmstat_mem_free": "Total free memory (GB)",
    "cpu_vmstat_mem_swpd": "Total virtual memory (GB)",
    "cpu_vmstat_procs_b": "Num of processes blocked and waiting for I/O",
    "cpu_vmstat_procs_r": "Num of processes running or waiting to run",
    "cpu_vmstat_swap_si": "Amount of memory swapped in from disk (/s)",
    "cpu_vmstat_swap_so": "Amount of memory swapped to disk (/s)",
    "cpu_vmstat_system_cs": "Num of context switches per sec",
    "cpu_vmstat_system_in": "Num of system interrupts per sec",
    "gpu_dcgm_correctable_remapped_rows": "Num of remapped rows for correctable errors",
    "gpu_dcgm_board_limit_violation": "Throttling duration due to board limit constraints (in us)",
    "gpu_dcgm_dec_utilization": "Decoder utilization (%)",
    "gpu_dcgm_ecc_dbe_aggregate_total": "Total num of double-bit persistent ECC errors",
    "gpu_dcgm_ecc_dbe_volatile_total": "Total num of double-bit volatile ECC errors",
    "gpu_dcgm_ecc_sbe_aggregate_total": "Total num of single-bit persistent ECC errors",
    "gpu_dcgm_ecc_sbe_volatile_total": "Total num of single-bit volatile ECC errors",
    "gpu_dcgm_enc_utilization": "Encoder utilization (%)",
    "gpu_dcgm_fb_free": "Framebuffer memory free (MB)",
    "gpu_dcgm_fb_used": "Framebuffer memory used (in MB)",
    "gpu_dcgm_fp16_active": "Ratio of cycles the fp16 pipes are active (%)",
    "gpu_dcgm_fp32_active": "Ratio of cycles the fp32 pipes are active (%)",
    "gpu_dcgm_fp64_active": "Ratio of cycles the fp64 pipes are active (%)",
    "gpu_dcgm_gpu_temp": "GPU temperature (in C)",
    "gpu_dcgm_gpu_utilization": "GPU utilization (%)",
    "gpu_dcgm_low_util_violation": "Throttling duration due to low utilization (us)",
    "gpu_dcgm_mem_copy_utilization": "GPU memory utilization (in %)",
    "gpu_dcgm_memory_clock": "GPU memory clock frequency (MHz)",
    "gpu_dcgm_memory_temp": "GPU memory temperature (C)",
    "gpu_dcgm_nvlink_bandwidth_total": "Total num of NVLink bandwidth counters for all lanes",
    "gpu_dcgm_nvlink_data_crc_error_count_total": "Total num of NVLink data CRC errors",
    "gpu_dcgm_nvlink_flit_crc_error_count_total": "Total num of NVLink flow-control CRC errors",
    "gpu_dcgm_nvlink_recovery_error_count_total": "Total num of NVLink recovery errors",
    "gpu_dcgm_nvlink_replay_error_count_total": "Total num of NVLink retries.",
    "gpu_dcgm_pcie_replay_counter": "GPU total num of PCIe retries",
    "gpu_dcgm_pcie_rx_throughput": "GPU total num of bytes received through PCIe RX via NVML (KB)",
    "gpu_dcgm_pcie_tx_throughput": "GPU total num of bytes transmitted through PCIe TX via NVML (KB)",
    "gpu_dcgm_power_usage": "GPU power draw (in W).",
    "gpu_dcgm_power_violation": "Throttling duration due to power constraints (us)",
    "gpu_dcgm_reliability_violation": "Throttling duration due to reliability constraints (us)",
    "gpu_dcgm_retired_pages_dbe": "Pages retired due to uncorrectable ECC double-bit errors",
    "gpu_dcgm_retired_pages_pending": "Pages pending retirement",
    "gpu_dcgm_retired_pages_sbe": "Pages retired due to correctable ECC single-bit errors",
    "gpu_dcgm_row_remap_failure": "Whether remapping of rows has failed",
    "gpu_dcgm_sm_active": "The ratio of cycles an SM has at least 1 warp assigned (%)",
    "gpu_dcgm_sm_clock": "SM clock frequency (MHz)",
    "gpu_dcgm_sm_occupancy": "Ratio of num of warps resident on an SM (%)",
    "gpu_dcgm_sync_boost_violation": "Throttling duration due to sync-boost constraints (us)",
    "gpu_dcgm_tensor_active": "Ratio of cycles the tensor pipe is active (%)",
    "gpu_dcgm_thermal_violation": "Throttling duration due to thermal constraints (us)",
    "gpu_dcgm_total_energy_consumption": "Total energy consumption since boot (mJ).",
    "gpu_dcgm_uncorrectable_remapped_rows": "Num of remapped rows for uncorrectable errors",
    "gpu_dcgm_vgpu_instance_license_status": "vGPU License status",
    "gpu_dcgm_xid_errors": "Value of the last XID error encountered"
}