metrics_descriptions = {
    "cpu_vmstat_mem_free": "Free Memory (GB)",
    "cpu_vmstat_cpu_id": "CPU time spent idle",
    "cpu_vmstat_cpu_sy": "CPU time spent on system (kernel) operations",
    "cpu_vmstat_cpu_us": "CPU time spent on user-level applications",
    "cpu_vmstat_cpu_wa": "CPU time spent waiting for I/O operations",
    "cpu_vmstat_io_bi": "Memory I/O Block Input (KB)",
    "cpu_vmstat_io_bo": "Memory I/O Block Output (KB)",
    "cpu_vmstat_mem_buff": "Memory used for buffers",
    "cpu_vmstat_mem_cache": "Memory used for cache",
    "cpu_vmstat_mem_free": "Free memory available in the system",
    "cpu_vmstat_mem_swpd": "Memory swapped out to disk",
    "cpu_vmstat_procs_b": "Number of processes blocked and waiting for I/O",
    "cpu_vmstat_procs_r": "Number of processes running or waiting to run",
    "cpu_vmstat_swap_si": "Memory swapped in from disk (pages)",
    "cpu_vmstat_swap_so": "Memory swapped out to disk (pages)",
    "cpu_vmstat_system_cs": "Context switches per second",
    "cpu_vmstat_system_in": "Interrupts per second",
    "gpu_dcgm_board_limit_violation": "Instances of board limit violations (e.g., power or thermal)",
    "gpu_dcgm_correctable_remapped_rows": "Corrected memory errors resulting in remapping",
    "gpu_dcgm_dec_utilization": "Utilization of the decoder engine",
    "gpu_dcgm_ecc_dbe_aggregate_total": "Total count of uncorrectable ECC double-bit errors",
    "gpu_dcgm_ecc_dbe_volatile_total": "Volatile count of uncorrectable ECC double-bit errors",
    "gpu_dcgm_ecc_sbe_aggregate_total": "Total count of correctable ECC single-bit errors",
    "gpu_dcgm_ecc_sbe_volatile_total": "Volatile count of correctable ECC single-bit errors",
    "gpu_dcgm_enc_utilization": "Utilization of the encoder engine",
    "gpu_dcgm_fb_free": "Free frame buffer memory",
    "gpu_dcgm_fb_used": "Used frame buffer memory",
    "gpu_dcgm_fp16_active": "Utilization of FP16 (half-precision) processing",
    "gpu_dcgm_fp32_active": "Utilization of FP32 (single-precision) processing",
    "gpu_dcgm_fp64_active":" Utilization of FP64 (double-precision) processing",
    "gpu_dcgm_gpu_temp": "GPU temperature",
    "gpu_dcgm_gpu_utilization": "Overall GPU utilization",
    "gpu_dcgm_low_util_violation": "Violations due to low utilization",
    "gpu_dcgm_mem_copy_utilization": "Memory copy engine utilization",
    "gpu_dcgm_memory_clock": "GPU memory clock speed",
    "gpu_dcgm_memory_temp": "GPU memory temperature",
    "gpu_dcgm_nvlink_bandwidth_total": "Total NVLink bandwidth",
    "gpu_dcgm_nvlink_data_crc_error_count_total": "Total CRC data errors on NVLink",
    "gpu_dcgm_nvlink_flit_crc_error_count_total": "Total CRC flit errors on NVLink",
    "gpu_dcgm_nvlink_recovery_error_count_total": "Total NVLink recovery errors",
    "gpu_dcgm_nvlink_replay_error_count_total": "Total NVLink replay errors",
    "gpu_dcgm_pcie_replay_counter": "Total PCIe replay events",
    "gpu_dcgm_pcie_rx_throughput": "PCIe receive (RX) throughput",
    "gpu_dcgm_pcie_tx_throughput": "PCIe transmit (TX) throughput",
    "gpu_dcgm_power_usage": "GPU power consumption",
    "gpu_dcgm_power_violation": "Instances of GPU power limit violations",
    "gpu_dcgm_reliability_violation": "GPU reliability violations",
    "gpu_dcgm_retired_pages_dbe": "Pages retired due to uncorrectable ECC double-bit errors",
    "gpu_dcgm_retired_pages_pending": "Pages pending retirement",
    "gpu_dcgm_retired_pages_sbe": "Pages retired due to correctable ECC single-bit errors",
    "gpu_dcgm_row_remap_failure": "Failures during row remapping in memory",
    "gpu_dcgm_sm_active": "Streaming multiprocessor (SM) activity",
    "gpu_dcgm_sm_clock": "SM clock speed",
    "gpu_dcgm_sm_occupancy": "SM occupancy rate",
    "gpu_dcgm_sync_boost_violation": "Synchronization boost violations",
    "gpu_dcgm_tensor_active": "Tensor core activity",
    "gpu_dcgm_thermal_violation": "Instances of thermal limit violations",
    "gpu_dcgm_total_energy_consumption": "Total energy consumed by the GPU",
    "gpu_dcgm_uncorrectable_remapped_rows": "Uncorrectable memory rows remapped",
    "gpu_dcgm_vgpu_instance_license_status": "Licensing status of virtual GPU instances",
    "gpu_dcgm_xid_errors": "GPU XID errors indicating hardware or driver issues"
}